# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-22 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='电影名')),
                ('director', models.CharField(default='', max_length=100, verbose_name='导演')),
                ('actor', models.CharField(default='', max_length=1000, verbose_name='演员')),
                ('releasetime', models.DateTimeField(default='')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载量')),
                ('star_one', models.IntegerField(default=0, verbose_name='一星数')),
                ('star_two', models.IntegerField(default=0, verbose_name='二星数')),
                ('star_three', models.IntegerField(default=0, verbose_name='三星数')),
                ('star_four', models.IntegerField(default=0, verbose_name='四星数')),
                ('star_five', models.IntegerField(default=0, verbose_name='五星数')),
                ('star_avg', models.FloatField(default=0, verbose_name='平均星数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('url', models.CharField(max_length=1000, verbose_name='电影资源链接')),
            ],
            options={
                'db_table': 'movie_information',
            },
        ),
        migrations.CreateModel(
            name='MovieKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, unique=True, verbose_name='关键字')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('movieInfomation', models.ManyToManyField(to='movie.MovieInfomation')),
            ],
            options={
                'db_table': 'movie_keyword',
            },
        ),
    ]
