# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-25 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phonenumber',
            field=models.CharField(max_length=11, unique=True, verbose_name='手机号'),
        ),
    ]
